-- MySQL Script generated by MySQL Workbench
-- Wed Nov  7 15:41:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipos` (
  `idTipos` INT NOT NULL,
  `Adaptado` TINYINT NULL,
  `Camas_casal` INT NULL,
  `TV` INT NULL,
  `Camas_solteiro` INT NULL,
  `Frigobar` INT NULL,
  PRIMARY KEY (`idTipos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reserva` (
  `idReserva` INT NOT NULL,
  `check-in` VARCHAR(45) NULL,
  `check-out` VARCHAR(45) NULL,
  `total` VARCHAR(45) NULL,
  `Reservacol` VARCHAR(45) NULL,
  `Tipos_idTipos` INT NOT NULL,
  PRIMARY KEY (`idReserva`),
  UNIQUE INDEX `check-in_UNIQUE` (`check-in` ASC) VISIBLE,
  INDEX `fk_Reserva_Tipos1_idx` (`Tipos_idTipos` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_Tipos1`
    FOREIGN KEY (`Tipos_idTipos`)
    REFERENCES `mydb`.`Tipos` (`idTipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idClientes` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Nacionalidade` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NULL,
  `Rua` VARCHAR(45) NULL,
  `Numero` INT NULL,
  `Bairro` VARCHAR(45) NULL,
  `Cidade` VARCHAR(45) NULL,
  `CEP` INT NULL,
  `Estado` VARCHAR(45) NULL,
  `Reserva_idReserva` INT NOT NULL,
  PRIMARY KEY (`idClientes`),
  INDEX `fk_Clientes_Reserva_idx` (`Reserva_idReserva` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_Reserva`
    FOREIGN KEY (`Reserva_idReserva`)
    REFERENCES `mydb`.`Reserva` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hoteis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hoteis` (
  `idHoteis` INT NOT NULL,
  `Cidade` VARCHAR(45) NULL,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idHoteis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Apartamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Apartamentos` (
  `idApartamento` INT NOT NULL,
  `Tipos_idTipos` INT NOT NULL,
  `Hoteis_idHoteis` INT NOT NULL,
  PRIMARY KEY (`idApartamento`),
  INDEX `fk_Apartamentos_Tipos1_idx` (`Tipos_idTipos` ASC) VISIBLE,
  INDEX `fk_Apartamentos_Hoteis1_idx` (`Hoteis_idHoteis` ASC) VISIBLE,
  CONSTRAINT `fk_Apartamentos_Tipos1`
    FOREIGN KEY (`Tipos_idTipos`)
    REFERENCES `mydb`.`Tipos` (`idTipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Apartamentos_Hoteis1`
    FOREIGN KEY (`Hoteis_idHoteis`)
    REFERENCES `mydb`.`Hoteis` (`idHoteis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Restaurante` (
  `idRestaurante` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `preço` INT NULL,
  PRIMARY KEY (`idRestaurante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`frigobar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`frigobar` (
  `idfrigobar` INT NOT NULL,
  `produto` VARCHAR(45) NULL,
  `preço` INT NULL,
  PRIMARY KEY (`idfrigobar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedidos` (
  `idPedidos` INT NOT NULL,
  `total` VARCHAR(45) NULL,
  `Restaurante_idRestaurante` INT NOT NULL,
  `frigobar_idfrigobar` INT NOT NULL,
  PRIMARY KEY (`idPedidos`),
  INDEX `fk_Pedidos_Restaurante1_idx` (`Restaurante_idRestaurante` ASC) VISIBLE,
  INDEX `fk_Pedidos_frigobar1_idx` (`frigobar_idfrigobar` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_Restaurante1`
    FOREIGN KEY (`Restaurante_idRestaurante`)
    REFERENCES `mydb`.`Restaurante` (`idRestaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_frigobar1`
    FOREIGN KEY (`frigobar_idfrigobar`)
    REFERENCES `mydb`.`frigobar` (`idfrigobar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lavanderia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lavanderia` (
  `idlavanderia` INT NOT NULL,
  `funcionario` VARCHAR(45) NULL,
  `serviço` VARCHAR(45) NULL,
  PRIMARY KEY (`idlavanderia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diaria` (
  `idDiaria` INT NOT NULL,
  `data` VARCHAR(45) NULL,
  `total` VARCHAR(45) NULL,
  `Diariacol` VARCHAR(45) NULL,
  `Pedidos_idPedidos` INT NOT NULL,
  `lavanderia_idlavanderia` INT NOT NULL,
  PRIMARY KEY (`idDiaria`),
  INDEX `fk_Diaria_Pedidos1_idx` (`Pedidos_idPedidos` ASC) VISIBLE,
  INDEX `fk_Diaria_lavanderia1_idx` (`lavanderia_idlavanderia` ASC) VISIBLE,
  CONSTRAINT `fk_Diaria_Pedidos1`
    FOREIGN KEY (`Pedidos_idPedidos`)
    REFERENCES `mydb`.`Pedidos` (`idPedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diaria_lavanderia1`
    FOREIGN KEY (`lavanderia_idlavanderia`)
    REFERENCES `mydb`.`lavanderia` (`idlavanderia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conta` (
  `idConta` INT NOT NULL,
  `Dia` VARCHAR(45) NULL,
  `Valor` VARCHAR(45) NULL,
  `Apartamentos_idApartamento` INT NOT NULL,
  `Diaria_idDiaria` INT NOT NULL,
  PRIMARY KEY (`idConta`),
  INDEX `fk_Conta_Apartamentos1_idx` (`Apartamentos_idApartamento` ASC) VISIBLE,
  INDEX `fk_Conta_Diaria1_idx` (`Diaria_idDiaria` ASC) VISIBLE,
  CONSTRAINT `fk_Conta_Apartamentos1`
    FOREIGN KEY (`Apartamentos_idApartamento`)
    REFERENCES `mydb`.`Apartamentos` (`idApartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conta_Diaria1`
    FOREIGN KEY (`Diaria_idDiaria`)
    REFERENCES `mydb`.`Diaria` (`idDiaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
